In [3]:
import mrcfile
with mrcfile.open('/home/useradmin/Project_cisTEM/mrcs/small_crown.mrc') as mrc:
    crown = mrc.data
with mrcfile.open('/home/useradmin/Project_cisTEM/mrcs/small_ribosome.mrc') as mrc:
    ribosome= mrc.data
mrc.close()
print(crown.shape)
print(ribosome.shape)

(17, 128, 128)
(17, 128, 128)


In [5]:
from scipy.linalg import svd
import numpy as np
recrown = np.reshape(crown, [128*128, 17])
# recrown = recrown - np.mean(recrown)
U, s, VT = svd(recrown)
print(U)
print(s)
print(VT)

[[-1.9028857e-02 -5.4411241e-04  3.7042806e-03 ...  3.2427958e-03
   1.3951624e-02  1.0090384e-02]
 [-1.8048961e-02 -1.6891430e-03  3.9690086e-03 ...  7.9404069e-03
   2.2647586e-03 -7.2293505e-03]
 [-6.7614368e-03 -8.7562716e-04 -3.3783726e-06 ... -1.8353282e-02
  -3.9675431e-03 -6.2329466e-03]
 ...
 [ 2.5548169e-03  8.0028577e-03 -1.5963135e-02 ...  9.9790472e-01
  -9.2918781e-04 -3.1762716e-04]
 [ 3.5613626e-03  6.1394707e-03 -2.0322688e-02 ... -9.2336949e-04
   9.9883968e-01 -2.5181964e-04]
 [ 3.2750312e-03  5.5065295e-03 -9.6959332e-03 ... -3.0848343e-04
  -2.5718648e-04  9.9965352e-01]]
[0.15304494 0.07030571 0.04258337 0.03415065 0.03161975 0.02796717
 0.02479132 0.02237203 0.02071577 0.01965723 0.01866986 0.01709895
 0.01463104 0.01278988 0.01127621 0.00953434 0.0069157 ]
[[ 0.20826302  0.22102869  0.23330176  0.2425162   0.24714106  0.25297472
   0.25845152  0.2602318   0.2604742   0.25931677  0.2571641   0.25413013
   0.24914803  0.24228883  0.23273739  0.22312419  0.21071088

In [12]:
# from scipy.linalg import svd
# import numpy as np
# recrown = np.reshape(crown, [128*128, 17])

recrown1 = recrown - np.mean(recrown)
print(np.mean(recrown[0]))

print(recrown[1])
# U, s, VT = svd(recrown)
# print(U)
# print(s)
# print(VT)

-0.00070754177
[-0.00068385 -0.00070089 -0.00067907 -0.00073937 -0.00068201 -0.00069919
 -0.00068168 -0.00074129 -0.00076049 -0.00061831 -0.00071239 -0.00051495
 -0.00053819 -0.00062698 -0.00080341 -0.00075123 -0.00047267]


In [14]:
np.mean(recrown, axis = 0)

array([ 5.0635225e-07,  1.9670047e-07,  5.2328460e-07, -4.4180442e-07,
       -5.5929496e-07, -2.9105723e-07, -6.3218289e-07, -1.1141465e-06,
       -1.1665456e-06, -6.2308993e-07, -5.4090907e-07, -4.4220539e-07,
        4.0849002e-07,  1.1876357e-06, -2.4694467e-07,  1.0147844e-06,
        2.2209342e-06], dtype=float32)

In [19]:
recrown = np.reshape(crown, [128*128, 17])

In [11]:
recrown[:,0]

array([-0.00073204, -0.00068385, -0.00052965, ...,  0.00015357,
        0.00064652,  0.00045179], dtype=float32)

In [7]:
loadings_test = np.zeros((17, 17))
for i in range(17):
    for j in range(17):
        loadings_test[i][j] = VT[i][j] * (s[i]) **2
        
loadings_test

array([[ 4.87809346e-03,  5.17710039e-03,  5.46456956e-03,
         5.68039725e-03,  5.78872417e-03,  5.92536445e-03,
         6.05364624e-03,  6.09534510e-03,  6.10102306e-03,
         6.07391280e-03,  6.02349108e-03,  5.95242724e-03,
         5.83573277e-03,  5.67507146e-03,  5.45135054e-03,
         5.22618290e-03,  4.93542905e-03],
       [ 1.55837967e-03,  1.61598055e-03,  1.51183439e-03,
         1.38744286e-03,  1.18113781e-03,  9.18603484e-04,
         6.56095450e-04,  3.57293702e-04,  2.89876329e-05,
        -2.89694512e-04, -6.03577455e-04, -9.11849483e-04,
        -1.18096355e-03, -1.38766442e-03, -1.55696933e-03,
        -1.66316693e-03, -1.61042521e-03],
       [-6.16687016e-04, -6.10445398e-04, -4.47569637e-04,
        -2.10064943e-04,  3.33816513e-05,  2.90735268e-04,
         4.61290592e-04,  5.38722675e-04,  5.66409342e-04,
         5.41349866e-04,  4.34559412e-04,  2.53562824e-04,
         1.87045601e-05, -2.24940206e-04, -4.17155450e-04,
        -5.55931438e-04, -5.4

In [30]:
VT

array([[ 0.20826302,  0.22102869,  0.23330176,  0.2425162 ,  0.24714106,
         0.25297472,  0.25845152,  0.2602318 ,  0.2604742 ,  0.25931677,
         0.2571641 ,  0.25413013,  0.24914803,  0.24228883,  0.23273739,
         0.22312419,  0.21071088],
       [ 0.3152769 ,  0.32693017,  0.30586028,  0.28069454,  0.23895682,
         0.18584332,  0.13273513,  0.07228434,  0.00586451, -0.0586083 ,
        -0.12211018, -0.18447691, -0.23892157, -0.28073937, -0.31499156,
        -0.33647648, -0.32580626],
       [-0.34008282, -0.33664078, -0.24682009, -0.11584398,  0.01840889,
         0.16033104,  0.25438675,  0.29708803,  0.31235632,  0.29853684,
         0.23964538,  0.13983165,  0.01031496, -0.1240472 , -0.23004766,
        -0.3065781 , -0.3026192 ],
       [-0.21183851, -0.21343431, -0.11404036,  0.02926226,  0.19744426,
         0.32429057,  0.36349404,  0.24820477,  0.01105208, -0.22038922,
        -0.36474562, -0.38078994, -0.26156312, -0.06342238,  0.13819075,
         0.2729689 

In [ ]:
variances = s**2 / (recrown.shape[0]-1)
explained_variances_ratio = variances / np.sum(variances)
explained_variances_ratio[0]
variances[0]

In [24]:
# create m x n Sigma matrix
Sigma = np.zeros((recrown.shape[0], recrown.shape[1]))
print(Sigma.shape)
# populate Sigma with n x n diagonal matrix
Sigma[:recrown.shape[1], :recrown.shape[1]] = np.diag(s)
# select
n_elements = 5
Sigma = Sigma[:, :n_elements]
Sigma.shape
VT = VT[:n_elements, :]
# reconstruct

B = U.dot(Sigma).dot(VT)
print(B.shape)
# # print(B.shape)
# # # # transform
# T = U.dot(Sigma)
# print(T.shape)

# # T = recrown.dot(VT.T)
# # print(T)
# # # print(T)

(16384, 17)
(16384, 17)


In [26]:
du = pd.DataFrame(U)
du.head()

0         1         2         3         4         5         6      \
0 -0.019029 -0.000544  0.003704 -0.000392  0.001122 -0.000251  0.002111   
1 -0.018049 -0.001689  0.003969 -0.003374  0.003689 -0.001845 -0.005210   
2 -0.006761 -0.000876 -0.000003  0.005868 -0.005747 -0.016530  0.013611   
3 -0.004949 -0.007709 -0.001490 -0.011179 -0.013386  0.008039  0.002508   
4 -0.007622 -0.002854 -0.012531 -0.002337 -0.010824 -0.013674 -0.013140   

      7         8         9      ...     16374     16375     16376     16377  \
0  0.001099 -0.000925  0.000935  ... -0.008690 -0.001156 -0.000842  0.006765   
1  0.005927  0.003821 -0.006742  ...  0.012515  0.002757  0.002354 -0.005480   
2 -0.008327 -0.023868  0.003745  ...  0.011290 -0.001437  0.001880  0.000358   
3 -0.006364  0.008640 -0.002712  ...  0.000677 -0.002095  0.001435  0.006604   
4  0.018126  0.005773  0.000998  ...  0.002912  0.001103  0.003591  0.004859   

      16378     16379     16380     16381     16382     16383  
0  0.002663  0.000415  0.018593  0.003243  0.013952  0.010090  
1 -0.000330 -0.002031 -0.013821  0.007940  0.002265 -0.007229  
2  0.000423  0.004244 -0.022647 -0.018353 -0.003968 -0.006233  
3 -0.006084  0.002839  0.006295  0.002585 -0.013188 -0.000143  
4 -0.002427  0.014012 -0.014781 -0.013200 -0.013625 -0.004070  

[5 rows x 16384 columns]

In [27]:
trun_s = s[0:4]
loadings_test = np.zeros((17, 5))
for i in range(17):
    for j in range(5):
        loadings_test[i][j] =  VT[j][i] * (s[j]) **2
        
loadings_test_df = pd.DataFrame(loadings_test, columns=["PC1", "PC2", "PC3", "PC4", "PC5"], index = [1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17])

loadings_test_df

PC1       PC2       PC3       PC4       PC5
1   0.004878  0.001558 -0.000617 -0.000247 -0.000256
2   0.005177  0.001616 -0.000610 -0.000249 -0.000203
3   0.005465  0.001512 -0.000448 -0.000133  0.000017
4   0.005680  0.001387 -0.000210  0.000034  0.000252
5   0.005789  0.001181  0.000033  0.000230  0.000363
6   0.005925  0.000919  0.000291  0.000378  0.000264
7   0.006054  0.000656  0.000461  0.000424  0.000029
8   0.006095  0.000357  0.000539  0.000289 -0.000244
9   0.006101  0.000029  0.000566  0.000013 -0.000383
10  0.006074 -0.000290  0.000541 -0.000257 -0.000307
11  0.006023 -0.000604  0.000435 -0.000425 -0.000057
12  0.005952 -0.000912  0.000254 -0.000444  0.000227
13  0.005836 -0.001181  0.000019 -0.000305  0.000346
14  0.005675 -0.001388 -0.000225 -0.000074  0.000253
15  0.005451 -0.001557 -0.000417  0.000161  0.000042
16  0.005226 -0.001663 -0.000556  0.000318 -0.000176
17  0.004935 -0.001610 -0.000549  0.000297 -0.000234

In [ ]:
l = B.reshape(17, 128, 128)
plt.imshow(l[0])

In [19]:
import matplotlib.pyplot as plt
r = np.reshape(T, [128, 128])
plt.imshow(r)


NameError: name 'T' is not defined

In [5]:
from sklearn.decomposition import TruncatedSVD


# svd
svd = TruncatedSVD(n_components=5)
result = svd.fit_transform(recrown)

gg = result.reshape(5, 128, 128)

plt.imshow(gg[0])

NameError: name 'plt' is not defined

In [20]:
import pandas as pd

df = pd.DataFrame(recrown)

df.head()

0         1         2         3         4         5         6   \
0 -0.000732 -0.000677 -0.000716 -0.000709 -0.000715 -0.000736 -0.000742   
1 -0.000684 -0.000701 -0.000679 -0.000739 -0.000682 -0.000699 -0.000682   
2 -0.000530 -0.000339 -0.000060  0.000059 -0.000418 -0.000261 -0.000248   
3 -0.000144  0.000082 -0.000482 -0.000625 -0.000344 -0.000618 -0.000442   
4 -0.000069 -0.000196  0.000002 -0.000386 -0.000421 -0.000539 -0.000525   

         7         8         9         10        11        12        13  \
0 -0.000689 -0.000727 -0.000712 -0.000716 -0.000692 -0.000709 -0.000708   
1 -0.000741 -0.000760 -0.000618 -0.000712 -0.000515 -0.000538 -0.000627   
2 -0.000373 -0.000318  0.000057 -0.000179 -0.000406 -0.000603 -0.000500   
3 -0.000225  0.000038 -0.000024  0.000013 -0.000189 -0.000103  0.000189   
4 -0.000467 -0.000208 -0.000608 -0.000271 -0.000096 -0.000321 -0.000576   

         14        15        16  
0 -0.000667 -0.000708 -0.000672  
1 -0.000803 -0.000751 -0.000473  
2 -0.000006  0.000236 -0.000391  
3 -0.000152  0.000015 -0.000068  
4 -0.000303 -0.000122  0.000500

In [ ]:
svd.components_
print(svd.explained_variance_)
loadings["PC1"].iloc[0] * np.sqrt(svd.explained_variance_[0])


In [ ]:
loadings = pd.DataFrame(svd.components_.T, columns=["PC1", "PC2", "PC3", "PC4", "PC5"], index = [1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17])

loadings

In [ ]:
t = 0
for i in loadings["PC2"]:
    t += i**2
    
t

In [21]:

loadings_correct = pd.DataFrame(svd.components_.T * np.sqrt(svd.explained_variance_), columns=["PC1", "PC2", "PC3", "PC4", "PC5"], index = [1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17])
loadings_correct 

PC1       PC2       PC3       PC4       PC5
1   0.000249  0.000173  0.000113 -0.000057  0.000063
2   0.000264  0.000180  0.000112 -0.000057  0.000050
3   0.000279  0.000168  0.000082 -0.000030 -0.000004
4   0.000290  0.000154  0.000039  0.000008 -0.000062
5   0.000295  0.000131 -0.000006  0.000053 -0.000090
6   0.000302  0.000102 -0.000053  0.000087 -0.000065
7   0.000309  0.000073 -0.000085  0.000097 -0.000007
8   0.000311  0.000040 -0.000099  0.000066  0.000060
9   0.000311  0.000003 -0.000104  0.000003  0.000095
10  0.000310 -0.000032 -0.000099 -0.000059  0.000076
11  0.000307 -0.000067 -0.000080 -0.000097  0.000014
12  0.000304 -0.000101 -0.000047 -0.000102 -0.000056
13  0.000298 -0.000131 -0.000003 -0.000070 -0.000086
14  0.000290 -0.000154  0.000041 -0.000017 -0.000062
15  0.000278 -0.000173  0.000077  0.000037 -0.000010
16  0.000267 -0.000185  0.000102  0.000073  0.000043
17  0.000252 -0.000179  0.000101  0.000068  0.000058

In [15]:
svd1 = TruncatedSVD(n_components=6)
result = svd1.fit_transform(recrown)
loadings = pd.DataFrame(svd1.components_.T, columns=["PC1", "PC2", "PC3", "PC4", "PC5", "PC6"], index = [1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17])
loadings

PC1       PC2       PC3       PC4       PC5       PC6
1   0.208263  0.315276  0.340083 -0.211840  0.256177  0.344789
2   0.221029  0.326930  0.336641 -0.213435  0.203114  0.150660
3   0.233302  0.305860  0.246820 -0.114040 -0.016827 -0.185459
4   0.242516  0.280694  0.115844  0.029263 -0.252117 -0.366997
5   0.247141  0.238957 -0.018409  0.197445 -0.363232 -0.261496
6   0.252975  0.185844 -0.160331  0.324291 -0.264222  0.037918
7   0.258452  0.132735 -0.254386  0.363494 -0.029006  0.271957
8   0.260232  0.072285 -0.297088  0.248204  0.243677  0.247525
9   0.260474  0.005865 -0.312356  0.011052  0.382996  0.001969
10  0.259317 -0.058608 -0.298537 -0.220390  0.307341 -0.214438
11  0.257164 -0.122110 -0.239645 -0.364746  0.056879 -0.238337
12  0.254130 -0.184477 -0.139832 -0.380789 -0.226702 -0.066823
13  0.249148 -0.238922 -0.010315 -0.261563 -0.346437  0.217318
14  0.242289 -0.280739  0.124047 -0.063422 -0.252987  0.368143
15  0.232738 -0.314992  0.230047  0.138191 -0.042488  0.205968
16  0.223124 -0.336477  0.306578  0.272968  0.175654 -0.158776
17  0.210711 -0.325806  0.302619  0.255041  0.234198 -0.355875

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components=6)
transformed_image = pca.fit_transform(recrown)
loadings1 = pd.DataFrame(pca.components_.T, columns=["PC1", "PC2", "PC3", "PC4", "PC5", "PC6"], index = [1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17])    
loadings1

PC1       PC2       PC3       PC4       PC5       PC6
1   0.208263  0.315283 -0.340077 -0.211835  0.256177  0.344790
2   0.221029  0.326936 -0.336642 -0.213429  0.203115  0.150658
3   0.233302  0.305866 -0.246807 -0.114038 -0.016826 -0.185461
4   0.242516  0.280695 -0.115849  0.029265 -0.252116 -0.367005
5   0.247141  0.238956  0.018411  0.197444 -0.363232 -0.261498
6   0.252975  0.185843  0.160351  0.324286 -0.264223  0.037925
7   0.258451  0.132732  0.254402  0.363489 -0.029007  0.271964
8   0.260232  0.072278  0.297085  0.248202  0.243675  0.247526
9   0.260474  0.005858  0.312347  0.011050  0.382996  0.001967
10  0.259317 -0.058613  0.298538 -0.220393  0.307342 -0.214435
11  0.257164 -0.122114  0.239641 -0.364750  0.056881 -0.238333
12  0.254130 -0.184481  0.139819 -0.380792 -0.226700 -0.066821
13  0.249148 -0.238921  0.010315 -0.261565 -0.346436  0.217322
14  0.242289 -0.280735 -0.124040 -0.063422 -0.252987  0.368143
15  0.232738 -0.314993 -0.230091  0.138200 -0.042489  0.205951
16  0.223124 -0.336472 -0.306588  0.272975  0.175653 -0.158782
17  0.210711 -0.325795 -0.302589  0.255043  0.234198 -0.355867

In [ ]:
r1 = svd.inverse_transform(result)
print(r1.shape)
r2 = np.reshape(r1, [17, 128, 128])
plt.imshow(r2[0])

In [ ]:
U, s, VT = svd(ribosome)
print(U)
print(s)
print(VT)